image: node:latest

stages:
  - build

publish-package:
  stage: build
  script:    
    - npm config set //gitlab.com/api/v4/projects/56689152/packages/npm/:_authToken ${NPM_TOKEN}
    - echo "@vercel-test:registry=https://gitlab.com/api/v4/projects/56689152/packages/npm/" > .npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH